import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { DeviceProvider } from "../context/DeviceContext";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import QueryProvider from "@/lib/QueryProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "../context/AuthContext";

const inter = Poppins({ subsets: ["latin"], weight: ["400", "700", "900", "600", "200", "300", "500"] });
const locales = ["en", "ar"];

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body
        // style={{ direction: locale === "ar" ? "rtl" : "ltr" }} ${locale === "ar" && "text-right"}
        className={`${inter.className} `}
      >
        <QueryProvider>
          <AuthProvider>
            <ToastContainer
              position="top-center"
              autoClose={3500}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              pauseOnFocusLoss
              pauseOnHover={false}
              theme="light"
            />

            <ReactQueryDevtools initialIsOpen={false} />

            <NextIntlClientProvider messages={messages}>
              <DeviceProvider>{children}</DeviceProvider>
            </NextIntlClientProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}

/*
there is a middleware that check on the existence of the token 
the token is verfird on app first loads 
user settings is saved in cache of react query 
 */
